### ISSUE TITLE
build issue `relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE`

### ISSUE THREAD

**Issue by alisterburt** [czimaginginstitute/AreTomo2#7]
Me again, struggling to build AT2 following the instructions

I'm working in a conda environment with the following dependencies:

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - torchvision
  - libtiff
  - python=3.10.6
  - pytorch-gpu
  - cmake
  - cudatoolkit=11.4
  - pytorch
  - fftw
  - cudatoolkit-dev
  - cxx-compiler=1.3
  - cudnn
  - dotnet=6.0
```

And getting the following error whilst building

```
software/AreTomo2/Lib/libmrcfile.a(CLoadExtHeader.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a PIE object; recompile with -fPIE`
```

Any ideas?
